# Taps
tap "homebrew/boneyard"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/completions"
tap "homebrew/core"
tap "homebrew/dupes"
tap "homebrew/services"
tap "homebrew/versions"
tap "homebrew/x11"
tap "kryptco/tap"
tap "nlf/dhyve"
tap "osx-cross/avr"
tap "px4/px4"
tap "rickard-von-essen/formulae"

# Binaries
brew "ack"
brew "openssl"
brew "alpine"
brew "libyaml"
brew "readline"
brew "ansible"
brew "apr-util"
brew "libnet"
brew "arping"
brew "docbook"
brew "asciidoc"
brew "auto-scaling"
brew "autoconf"
brew "autojump", args: ["HEAD"]
brew "libusb-compat"
brew "avrdude"
brew "aws-elasticbeanstalk"
brew "awscli"
brew "bats", args: ["HEAD"]
brew "bazaar"
brew "beecrypt"
brew "berkeley-db"
brew "bmake"
brew "boost-python"
brew "gettext"
brew "popt"
brew "byobu"
brew "lzo"
brew "cdrtools"
brew "cloog"
brew "cloud-watch"
brew "cmake"
brew "colordiff"
brew "colorsvn"
brew "cscope"
brew "ctags"
brew "cunit"
brew "libev"
brew "curl", args: ["with-nghttp2"]
brew "cvs"
brew "czmq"
brew "darcs"
brew "dash"
brew "dbus"
brew "dep"
brew "dfu-programmer"
brew "direnv"
brew "libksba"
brew "pth"
brew "dirmngr"
brew "dnsmasq"
brew "docbook-xsl"
brew "docker-clean"
brew "docker-machine"
brew "doctl"
brew "dos2unix"
brew "doxygen"
brew "nettle"
brew "duplicity"
brew "ec2-ami-tools"
brew "elasticsearch"
brew "elixir"
brew "elixir-build"
brew "emacs"
brew "etcd"
brew "findutils"
brew "fish"
brew "libogg"
brew "flac"
brew "fleetctl"
brew "sdl"
brew "fs-uae"
brew "gcc"
brew "gcc@4.8"
brew "gcutil"
brew "gdb"
brew "gdk-pixbuf"
brew "gdrive"
brew "geoip"
brew "gist"
brew "git"
brew "git-extras"
brew "git-lfs"
brew "git-number"
brew "glide"
brew "gnu-getopt"
brew "gnu-prolog"
brew "gnu-tar"
brew "gnupg@1.4"
brew "gpg-agent"
brew "gradle"
brew "libtool"
brew "graphviz"
brew "grep"
brew "gron"
brew "groovy"
brew "heroku"
brew "ht"
brew "htop"
brew "hub"
brew "imagemagick"
brew "influxdb"
brew "libsndfile"
brew "ossp-uuid"
brew "yajl"
brew "io"
brew "ipmitool"
brew "irssi"
brew "oniguruma"
brew "jq"
brew "json-c"
brew "jsoncpp"
brew "kapacitor"
brew "kubernetes-cli"
brew "kubernetes-helm"
brew "lame"
brew "lastpass-cli"
brew "leiningen"
brew "lhasa"
brew "libcroco"
brew "libidn"
brew "libsodium"
brew "libssh2"
brew "libxslt"
brew "libyubikey"
brew "lighttpd"
brew "links"
brew "logstash"
brew "lua"
brew "luajit"
brew "macvim"
brew "makedepend"
brew "markdown"
brew "mas"
brew "moreutils"
brew "mp3wrap"
brew "msmtp"
brew "ncftp"
brew "neon"
brew "neovim", args: ["HEAD"]
brew "netdata"
brew "nginx"
brew "ngrep"
brew "nmap"
brew "pandoc"
brew "tree"
brew "pass"
brew "peco"
brew "pinentry-mac"
brew "plan9port"
brew "proj"
brew "pstree"
brew "pv"
brew "pwgen"
brew "qemu", args: ["with-sdl2"]
brew "qt"
brew "quilt"
brew "reattach-to-user-namespace"
brew "redis"
brew "restic"
brew "rpm"
brew "rpm2cpio"
brew "s3cmd"
brew "sbt"
brew "scala"
brew "scons"
brew "sgrep"
brew "shared-mime-info"
brew "shellcheck"
brew "sleepwatcher", restart_service: true
brew "smake"
brew "smartmontools"
brew "smlnj"
brew "squashfs"
brew "stlviewer"
brew "stm32flash"
brew "utf8proc"
brew "subversion"
brew "swig"
brew "sysdig"
brew "tarsnap"
brew "tcsh"
brew "terraform"
brew "testdisk"
brew "texi2html"
brew "the_silver_searcher"
brew "tmux-mem-cpu-load"
brew "tomcat@7"
brew "topgit"
brew "unixodbc"
brew "unrar"
brew "vault"
brew "vault-cli"
brew "wget"
brew "wireshark"
brew "xclip"
brew "xmlto"
brew "yadm"
brew "ykpers"
brew "ykman"
brew "youtube-dl"
brew "yubico-piv-tool"
brew "nlf/dhyve/dhyve", args: ["HEAD"]
brew "osx-cross/avr/avr-gcc"
brew "px4/px4/gcc-arm-none-eabi"
brew "rickard-von-essen/formulae/hid_listen"

# AppStore Applications
mas "Affinity Designer", id: 824171161
mas "Affinity Photo", id: 824183456
mas "Bee", id: 726099620
mas "Clari3D_Free", id: 512516629
mas "DaisyDisk", id: 411643860
mas "Disk Drill Media Recovery", id: 431224317
mas "Growl", id: 467939042
mas "Icon Glue", id: 599582932
mas "iGrandDesigner", id: 1253462716
mas "Install macOS Sierra Public Beta", id: 1073263501
mas "Keynote", id: 409183694
mas "LastPass", id: 926036361
mas "LimeChat", id: 414030210
mas "Microsoft OneNote", id: 784801555
mas "Microsoft Remote Desktop", id: 715768417
mas "Monit", id: 1014850245
mas "Moom", id: 419330170
mas "Numbers", id: 409203825
mas "OmniGraffle", id: 711830901
mas "OneDrive", id: 823766827
mas "Pages", id: 409201541
mas "Pocket", id: 568494494
mas "Remote Desktop - VNC", id: 472995993
mas "SketchBook", id: 863486266
mas "Slack", id: 803453959
mas "The Journalist", id: 764147223
mas "Time Out", id: 402592703
mas "Twitter", id: 409789998
mas "WhatsApp", id: 1147396723
mas "Wunderlist", id: 410628904
mas "Xcode", id: 497799835
mas "Xee³", id: 639764244
