#!/usr/bin/env bash
set -o nounset

system_type=$(uname -s)
export system_type
export PATH=/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

# -- OS / Distribution specific bootstrap --

if [ "$system_type" = "Darwin" ]; then
  "$DIR/bootstrap.darwin"
fi

if [ "$system_type" = "Linux" ]; then
  dist=$(grep ^ID= /etc/os-release | cut -d= -f2)

  if [ "$dist" = "fedora" ]; then
    "$DIR/bootstrap.fedora"
  fi

  if [ "$dist" = "debian" ]; then
    "$DIR/bootstrap.debian"
  fi

  # "$DIR/bootstrap.linux"

fi


# -- Generic bootstrap --

mkdir -p "$HOME/local"
mkdir -p "$HOME/bin"
mkdir -p "$HOME/go"

# install homebrew if it's missing
if ! command -v brew >/dev/null 2>&1; then
  echo "Installing homebrew"
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

. ~/.bash_profile

if [ -f "$HOME/.Brewfile" ]; then
  echo "Updating homebrew bundle"
  brew bundle --global
fi

echo "Installing Tmux Plugin Manager"
if [ ! -d "$HOME/.config/tmux/plugins/tpm" ]; then
  mkdir -p "$HOME/.config/tmux/plugins"
  git clone https://github.com/tmux-plugins/tpm "$HOME/.config/tmux/plugins/tpm"
fi

echo "Installing Kitty Themse"
if [ ! -d "$HOME/.config/kitty/kitty-themes" ]; then
  mkdir -p "$HOME/.config/kitty"
  git clone git@github.com:dexpota/kitty-themes.git "$HOME/.config/kitty/kitty-themes"
fi

echo "Installing Vim plug and Vim plugins"
if [ ! -d "$HOME/.vim/autoload/plug.vim" ]; then
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  vim +PluginInstall
fi

echo "Installing fisherman"
if [ ! -f "$HOME/.config/fish/functions/fisher.fish" ]; then
  curl -Lo "$HOME/.config/fish/functions/fisher.fish" --create-dirs https://git.io/fisher
  fish -c 'fisher'
fi

echo "Python 3 Modules"
cat $HOME/.pkg.py3 | xargs pip3 install --user

echo "Installing ASDF VM"
git clone https://github.com/asdf-vm/asdf.git $HOME/.asdf --branch v0.10.2
source $HOME/.asdf/asdf.fish
cat $HOME/.asdf-plugins | xargs -I= asdf plugin add =

echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:rickard-von-essen/dotfiles.git"
