#!/usr/bin/env bash
set -o nounset

system_type=$(uname -s)
export system_type
export PATH=/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

# -- OS / Distribution specific bootstrap --

if [ "$system_type" = "Darwin" ]; then
  "$DIR/bootstrap.darwin"
fi

if [ "$system_type" = "Linux" ]; then
  dist=$(grep ^ID= /etc/os-release | cut -d= -f2)

  if [ "$dist" = "fedora" ]; then
    "$DIR/bootstrap.fedora"
  fi

  if [ "$dist" = "debian" ]; then
    "$DIR/bootstrap.debian"
  fi

  # "$DIR/bootstrap.linux"

fi


# -- Generic bootstrap --

mkdir -p "$HOME/local"
mkdir -p "$HOME/bin"
mkdir -p "$HOME/go"

echo "Installing Tmux Plugin Manager"
if [ ! -d "$HOME/.config/tmux/plugins/tpm" ]; then
  mkdir -p "$HOME/.config/tmux/plugins"
  git clone https://github.com/tmux-plugins/tpm "$HOME/.config/tmux/plugins/tpm"
fi

echo "Installing Vundle and Vim plugins"
if [ ! -d "$HOME/.vim/bundle/Vundle.vim" ]; then
  git clone https://github.com/VundleVim/Vundle.vim.git "$HOME/.vim/bundle/Vundle.vim"
  vim +PluginInstall +qall
  python3 "$HOME/.vim/bundle/YouCompleteMe/install.py" --clang-completer --go-completer --js-completer --java-completer
fi

echo "Installing fisherman"
if [ ! -f "$HOME/.config/fish/functions/fisher.fish" ]; then
  curl -Lo "$HOME/.config/fish/functions/fisher.fish" --create-dirs https://git.io/fisher
  fish -c 'fisher'
fi

echo "Python 3 Modules"
cat $HOME/.pkg.py3 | xargs pip3 install --user

echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:rickard-von-essen/dotfiles.git"
