#!/usr/bin/env bash

system_type=$(uname -s)
export PATH=/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin

if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi

  ln -s /usr/local/opt/tarsnap-gui/Tarsnap.app /Applications/Tarsnap.app
  ln -s /usr/local/opt/macvim/MacVim.app /Applications/MacVim.app

  if [ -d "$HOME/.iterm2" ]; then
    echo "Setting iTerm preference folder"
    defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.iterm2"
  fi
fi

if [ ! -d "$HOME/.vim/bundle/Vundle.vim" ]; then
  git clone https://github.com/VundleVim/Vundle.vim.git "$HOME/.vim/bundle/Vundle.vim"
  vim +PluginInstall +qall
  python "$HOME/.vim/bunlde/YouCompleteMe/install.py" --clang-completer --go-completer --js-completer --java-completer
fi

if [ ! -f "$HOME/.config/fish/functions/fisher.fish" ]; then
  curl -Lo "$HOME/.config/fish/functions/fisher.fish" --create-dirs https://git.io/fisher
  fish -c 'fisher'
fi

echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:rickard-von-essen/dotfiles.git"
